name: Android CI

on:
  push:
     tags:
     - '*.*.*'
jobs:
  build:
   name: "Build apk / app bundle"
   runs-on: ubuntu-latest
 steps: 
 - uses: actions/checkout@v2.4.0
 - name: Configure Environment
 
 env: 
  RUN_NUMBER: ${{ gitub.run.number}}
  run: 
    echo"VERSION_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    echo"VERSION_NAME=${{&RUN_NUMBER+100}}" >> $GITHUB_ENV
    
  - name: setup java SDK
    uses: actions/setup-java@2.3.1
    with:
       java-version: 11
       distribution: 'temurin'
  - name: Setup Android SDk tools
    uses: android-actions/setup-android@v2.0.2
  - name: Get the Gadle Dependencies
    run: ./gradle android@Dependencies
  - name: Build APK
    run: ./gradle assembleDebug -PversionCode -PversionName=&VERSION_NAME
  
